spring:
    application: 
        name: api-gateway
    main:
        web-application-type: reactive    
    cloud:
        config:
            enabled: false
    # gateway:
    #   routes:
    #     - id: customer-service
    #       uri: lb://customer-service
    #       predicates:
    #         - Path=/api/customer/**
          
    #     - id: business-service
    #       uri: lb://business-service
    #       predicates:
    #         - Path=/api/business/**
          
    #     - id: category-service
    #       uri: lb://category-service
    #       predicates:
    #         - Path=/api/category/**
eureka:
  client:
    instance:
      prefer-ip-address: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8080

grpc:
  client:
    category-service:
      address: 'discovery:///category-service'
      negotiationType: plaintext

