spring:
    cloud:
        config:
            enabled: false
    application:
        name: category-service
    datasource:
        url: jdbc:sqlserver://localhost:1433;databaseName=micro_category;encrypt=true;trustServerCertificate=true
        username: sa
        password: dangnam
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:
        hibernate:
          ddl-auto: update
          show-sql: true
          dialect: org.hibernate.dialect.SQLServerDialect
    
server:
    port: 7777
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
grpc:
  server:
    port: 9091

logging:
  level:
    io.grpc: DEBUG
    net.devh: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
