eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false # chi dung dev

server:
  port: 8761
spring:
  cloud:
    config:
      enabled: false
    
